Fix message

diff --git a/scripts/ssl b/scripts/ssl
--- a/scripts/ssl
+++ b/scripts/ssl
@@ -12,7 +12,7 @@ else
 	exit 0
 fi
 
-command -v domanager &> /dev/null || { echo "Git is a required dependency for ${0}"; exit; }
+command -v domanager &> /dev/null || { echo "domanager is a required dependency for ${0}"; exit; }
 
 ( cd $AA_CONFIGDIR && domanager )
 echo '
